version: '3.9'
services:
  messagedb:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=message_db
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@messagedb:5432/message_db?sslmode=disable
    depends_on:
      - messagedb
    entrypoint: ["/app/wait-for.sh", "messagedb:5432","--", "/app/start.sh"]
    command: "/app/main"