// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: conversation.sql

package db

import (
	"context"
	"database/sql"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO "Conversation" (Unread, Last, Messages)
VALUES ($1, $2, $3)
RETURNING id, unread, last, messages
`

type CreateConversationParams struct {
	Unread   int32         `json:"unread"`
	Last     sql.NullInt64 `json:"last"`
	Messages sql.NullInt64 `json:"messages"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.Unread, arg.Last, arg.Messages)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Unread,
		&i.Last,
		&i.Messages,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM "Conversation"
WHERE ID = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, unread, last, messages
FROM "Conversation"
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetConversation(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Unread,
		&i.Last,
		&i.Messages,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, unread, last, messages
FROM "Conversation"
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListConversationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Unread,
			&i.Last,
			&i.Messages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE "Conversation"
SET (Unread, Last, Messages) = ($2, $3, $4)
WHERE ID = $1
returning id, unread, last, messages
`

type UpdateConversationParams struct {
	ID       int64         `json:"id"`
	Unread   int32         `json:"unread"`
	Last     sql.NullInt64 `json:"last"`
	Messages sql.NullInt64 `json:"messages"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, updateConversation,
		arg.ID,
		arg.Unread,
		arg.Last,
		arg.Messages,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Unread,
		&i.Last,
		&i.Messages,
	)
	return i, err
}
