// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Conversation struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
}

type Message struct {
	ID        int64     `json:"id"`
	From      string    `json:"from"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	ConvID    int64     `json:"convID"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	UserID       int64     `json:"userID"`
	RefreshToken string    `json:"refreshToken"`
	UserAgent    string    `json:"userAgent"`
	ClientIp     string    `json:"clientIp"`
	IsBlocked    bool      `json:"isBlocked"`
	ExpiresAt    time.Time `json:"expiresAt"`
	CreatedAt    time.Time `json:"createdAt"`
}

type User struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	HashedPw  string         `json:"hashedPw"`
	Image     sql.NullString `json:"image"`
	Status    sql.NullString `json:"status"`
	CreatedAt time.Time      `json:"createdAt"`
}

type UserConversation struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userID"`
	ConvID int64 `json:"convID"`
}
