// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "Users" (
    name,
    email,
    hashed_pw,
    image,
    status
  )
VALUES ($1, $2, $3, $4, $5)
RETURNING $1,
  $2,
  $4,
  $5
`

type CreateUserParams struct {
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	HashedPw string         `json:"hashedPw"`
	Image    sql.NullString `json:"image"`
	Status   sql.NullString `json:"status"`
}

type CreateUserRow struct {
	Column1 interface{} `json:"column1"`
	Column2 interface{} `json:"column2"`
	Column3 interface{} `json:"column3"`
	Column4 interface{} `json:"column4"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.HashedPw,
		arg.Image,
		arg.Status,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.Column1,
		&i.Column2,
		&i.Column3,
		&i.Column4,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id,
  name,
  email,
  image,
  status
FROM "Users"
WHERE id = $1
LIMIT 1
`

type GetUserRow struct {
	ID     int64          `json:"id"`
	Name   string         `json:"name"`
	Email  string         `json:"email"`
	Image  sql.NullString `json:"image"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Image,
		&i.Status,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id,
  name,
  email,
  image,
  status
FROM "Users"
ORDER BY id
`

type ListUsersRow struct {
	ID     int64          `json:"id"`
	Name   string         `json:"name"`
	Email  string         `json:"email"`
	Image  sql.NullString `json:"image"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Image,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
